### ISSUE TITLE
toHaveClass should wrap existing matcher

### ISSUE THREAD

**Issue by jcarlson** [PsychoLlama/expect-enzyme#1]
My test suite already has a custom matcher called `toHaveClass` (and also `toNotHaveClass`). So `expect-enzyme` clashes with this existing matcher and breaks tests which are expecting the non-enzymified version of the matcher.

Looks like it should be trivial to `addEnzymeSupport` to resolve this...

**Comment by PsychoLlama** [comment]
Hey @jcarlson! Sorry things are breaking. You're right, it should check for an existing method before registering a new one. What type of value is `.toHaveClass` expecting on your side?

**Comment by jcarlson** [comment]
My matchers are expecting a node and a string to assert that the node has that class. Such as:

```jsx
class MyComponent extends Component {
  render () {
    return <div className='my-component'>Hello!</div>
  }
}

let rendered = ReactDOM.render(<MyComponent />, document.createElement('div'))
let node = ReactDOM.findDOMNode(rendered)
expect(node).toHaveClass('my-component')
```

Here's my matchers:

```javascript
expect.extend({
  toHaveClass (className) {
    expect.assert(
      this.actual.classList ?
        this.actual.classList.contains(className) :
        false,
      'Expected class list %s to contain  %s.',
      this.actual.classList ?
        Array.from(this.actual.classList) :
        '(not a DOM element)',
      className
    )
    return this
  },

  toNotHaveClass (className) {
    expect.assert(
      this.actual.classList ?
        !this.actual.classList.contains(className) :
        true,
      'Expected class list %s to not contain  %s.',
      this.actual.classList ?
        Array.from(this.actual.classList) :
        '(not a DOM element)',
      className
    )
    return this
  }
})
```

**Comment by PsychoLlama** [comment]
Sweet, thanks!
I'm hoping to add a few new features this weekend, I'll be sure to prioritize this.

**Comment by PsychoLlama** [comment]
I've just pushed out [`v0.13.2`](https://www.npmjs.com/package/expect-enzyme) which should resolve your issue. Just be sure you import (and extend) your custom assertions before loading `expect-enzyme`. I'm closing this issue for now, but feel free to re-open if you need!
