### ISSUE TITLE
Allow toNotHaveRendered to be called even for non-existent components

### ISSUE THREAD

**Issue by dglsparsons** [PsychoLlama/expect-enzyme#18]
e.g. 
let something = wrapper.find("uhteonaushentoauhenoas");
expect(something).toNotExist();
=> true
expect(something).toNotHaveRendered();
=> :boom: // If it doesn't exist.. it hasn't rendered, so this should return `true`

**Comment by dglsparsons** [comment]
Current behaviour is to Error if the node does not exist 
```
Error: Method “equals” is only meant to be run on a single node. 0 found instead.
      at ShallowWrapper.single (node_modules/enzyme/build/ShallowWrapper.js:1516:17)
      at ShallowWrapper.equals (node_modules/enzyme/build/ShallowWrapper.js:582:21)
      at Expectation.<anonymous> (node_modules/expect-enzyme/dist/assertions.js:380:27)
      at Expectation.assertion [as toHaveRendered] (node_modules/expect-enzyme/dist/assertions.js:174:23)
      at Expectation.<anonymous> (node_modules/expect-enzyme/dist/assertions.js:102:17)
      at Expectation.assertion [as toNotHaveRendered] (node_modules/expect-enzyme/dist/assertions.js:174:23
     ...
```

**Comment by PsychoLlama** [comment]
Interesting... I agree, `.toNotHaveRendered()` should pass if the node doesn't exist. I'm wondering what should happen if arguments are passed to the assertion. It might give accidental false positives. I'm leaning towards throwing an error if the node is nonexistent and any arguments (including `null`) are given.

**Comment by PsychoLlama** [comment]
I haven't forgotten about you! Promise!

[I built the thing](https://github.com/PsychoLlama/expect-enzyme/pull/21), but while doing it I realized there was a lot of duplication with `expect(...).toExist()`/`.toNotExist()`. The main purpose of `.toHaveRendered(...)` is to check for JSX equality:

```js
expect(shallow(<Component {...props} />)).toHaveRendered(<div onClick={props.onClick}>)
```

Since `undefined` isn't a valid render value, I'm leaning towards just throwing an error if no arguments are passed recommending `.to(Not)Exist` instead.

Another software project has been keeping me busy lately, so it might be just a bit longer before I can push a fix for this, but in the meantime I'll publish [the other fix](https://github.com/PsychoLlama/expect-enzyme/pull/20) for `.toHaveProp` as its own version.

**Comment by dglsparsons** [comment]
Agreed that there is almost certainly a lot of duplication with `toExist() / toNotExist()`. While the main purpose is to check for JSX equality, it's been a bit of a bane of mine writing tests using this - nearly always i'm writing tests that first check it exists, and then check it rendered the correct thing (which is sensible), but then the inversion is a pain - sometimes things _do_ exist, but don't render anything, sometimes they _don't_ exist (and therefore don't render anything).... 

I guess what I was really hoping for was a simpler way of writing that kind of test... if it was possible to call `toNotHaveRendered()` (even with args), and have it pass on a non-existent component, it would provide a unified way to check that something wasn't rendered :)

I guess the ideal behaviour would be 
- `toHaveRendered` - fails (without error) if it is called on something that doesn't exist (regardless of args). No args implies it has rendered _something_, so should fail in this case..
- `toNotHaveRendered` - passes (without error) if it is called on something that doesn't exist (regardless of args). 

I think that would be more intuitive...

**Comment by PsychoLlama** [comment]
Hey, I'm all for less test boilerplate. I've added checks in both `.toHaveRendered()` and `.toNotHaveRendered()`. Now you can use either without args, and both respond better when the element doesn't exist.

Calling `.toHaveRendered()` without args will pass if the element exists and didn't render `null`.

Calling `.toNotHaveRendered()` without args will pass if the element doesn't exist or it rendered `null`. If any arguments are given and the element doesn't exist, the assertion will fail in an effort to prevent false positives.

```
Error: Expected element not to match, but it didn't exist
```

I've pushed the new behavior as `v1.2.0`. Lemme know how it works for ya!

**Comment by dglsparsons** [comment]
That sounds awesome - i'll give it a try next :)
