### ISSUE TITLE
Allow Comparison of Object Props

### ISSUE THREAD

**Issue by dglsparsons** [PsychoLlama/expect-enzyme#19]
Current behaviour of `toHaveProp` performs object comparison (i.e. `===`). This is tricky when you are comparing against a different but equivalent object. 

e.g. 
```javascript
let something = shallow(<Something value={{"one": 1}} />);
expect(something).toHaveProp("value", { "one": 1}); // will fail because they are different object instances
```
Current workaround is to do 
```javascript
let something = shallow(<Something value={{"one": 1}} />);
expect(something.prop("value")).toEqual({ "one": 1}); // will pass as the values are equivalent
```
Which feels overly en-cumbersome.

**Comment by PsychoLlama** [comment]
You're right! That was an oversight on my part. Adding it _should_ be backwards compatible (same reference always equals itself).

**Comment by dglsparsons** [comment]
I wonder if there's ever an instance where you want to compare using object comparison... i.e. checking that the same object is passed as a prop. May be a case here for another extension, i.e. `toHavePropOf()` or some better name implying object equality...
