### ISSUE TITLE
add support for enzyme@3

### ISSUE THREAD

**Issue by andyianriley** [PsychoLlama/expect-enzyme#25]

**Comment by PsychoLlama** [comment]
Indeed 🤔 

I was hoping to knock this out this weekend, but bugs and deadlines of another project disagreed. We are currently locked in epic battle.

:soon:

**Comment by PsychoLlama** [comment]
`expect-enzyme@1.3.0` is live with support for Enzyme 3/React 16 :tada: (PR #26)

@andyianriley if you run into any problems on the new version, just lemme know 👍
